-- CreateTable
CREATE TABLE `notificatie` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ORDER_ID` INTEGER NOT NULL,
    `TEXT` VARCHAR(191) NOT NULL,
    `TYPE` ENUM('BETALINGSVERZOEK', 'BETALINGONTVANGEN', 'ORDERVERZENDBAAR') NOT NULL,
    `STATUS` ENUM('GELEZEN', 'ONGELEZEN', 'NIEUW') NOT NULL,
    `DATUM` DATE NOT NULL,
    `USER_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `notificatie` ADD CONSTRAINT `FK_NOTIFICATIE_BESTELLING_ID` FOREIGN KEY (`ORDER_ID`) REFERENCES `bestelling`(`ID`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `notificatie` ADD CONSTRAINT `FK_NOTIFICATIE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user`(`ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
