-- CreateTable
CREATE TABLE `admin` (
    `ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `bedrijf` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ACCOUNTSINDS` DATE NOT NULL,
    `ADRES` VARCHAR(255) NOT NULL,
    `BETALINGSINFO` ENUM('FACTUUR', 'PAYPAL', 'BANCONTACT', 'VISA', 'MAESTRO', 'OVERSCHRIJVING') NOT NULL,
    `BTWNUMMER` VARCHAR(255) NOT NULL,
    `CONTACTGEGEVENS` JSON NOT NULL,
    `ISACTIEFKLANT` BOOLEAN NOT NULL DEFAULT false,
    `ISACTIEFLEVERANCIER` BOOLEAN NOT NULL DEFAULT false,
    `LOGOIMAGE` VARCHAR(255) NOT NULL,
    `NAAM` VARCHAR(255) NOT NULL,
    `SECTOR` VARCHAR(255) NOT NULL,
    `ADMIN_ID` INTEGER NULL,

    UNIQUE INDEX `BTWNUMMER`(`BTWNUMMER`),
    UNIQUE INDEX `NAAM`(`NAAM`),
    INDEX `FK_bedrijf_ADMIN_ID`(`ADMIN_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `bedrijfverandering` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `AANGEVRAAGDOP` DATETIME(6) NOT NULL,
    `ACCOUNTSINDS` DATE NOT NULL,
    `ADRES` VARCHAR(255) NOT NULL,
    `BETALINGSINFO` ENUM('FACTUUR', 'PAYPAL', 'BANCONTACT', 'VISA', 'MAESTRO', 'OVERSCHRIJVING') NOT NULL,
    `CONTACTGEGEVENS` JSON NOT NULL,
    `ISACTIEFKLANT` BOOLEAN NOT NULL DEFAULT false,
    `ISACTIEFLEVERANCIER` BOOLEAN NOT NULL DEFAULT false,
    `ISAFGEKEURD` BOOLEAN NOT NULL DEFAULT false,
    `ISGOEDGEKEURD` BOOLEAN NOT NULL DEFAULT false,
    `LOGOIMAGE` VARCHAR(255) NOT NULL,
    `SECTOR` VARCHAR(255) NOT NULL,
    `AANGEVRAAGDDOOR_ID` INTEGER NOT NULL,
    `BEDRIJF_ID` INTEGER NOT NULL,

    INDEX `FK_bedrijfverandering_AANGEVRAAGDDOOR_ID`(`AANGEVRAAGDDOOR_ID`),
    INDEX `FK_bedrijfverandering_BEDRIJF_ID`(`BEDRIJF_ID`),
    UNIQUE INDEX `bedrijfverandering_AANGEVRAAGDDOOR_ID_BEDRIJF_ID_key`(`AANGEVRAAGDDOOR_ID`, `BEDRIJF_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `bestelling` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BEDRAG` DOUBLE NOT NULL,
    `BETAALDAG` DATE NOT NULL,
    `BETALINGSSTATUS` VARCHAR(255) NOT NULL,
    `DATUMGEPLAATST` DATE NOT NULL,
    `DATUMLAATSTEBETALINGSHERINNERING` DATE NULL,
    `HEEFTBETALINGSHERINNERING` BOOLEAN NOT NULL DEFAULT false,
    `LEVERADRES` VARCHAR(255) NOT NULL,
    `ORDERID` VARCHAR(255) NOT NULL,
    `ORDERSTATUS` VARCHAR(255) NOT NULL,
    `USER_ID` INTEGER NULL,
    `KLANT_ID` INTEGER NOT NULL,
    `LEVERANCIER_ID` INTEGER NOT NULL,

    INDEX `FK_bestelling_KLANT_ID`(`KLANT_ID`),
    INDEX `FK_bestelling_LEVERANCIER_ID`(`LEVERANCIER_ID`),
    INDEX `FK_bestelling_USER_ID`(`USER_ID`),
    UNIQUE INDEX `bestelling_LEVERANCIER_ID_ORDERID_key`(`LEVERANCIER_ID`, `ORDERID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `bestelling_product` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `AANTAL` INTEGER NOT NULL,
    `price` DOUBLE NOT NULL,
    `BESTELLING_ID` INTEGER NOT NULL,
    `PRODUCT_ID` INTEGER NOT NULL,

    INDEX `FK_bestelling_product_BESTELLING_ID`(`BESTELLING_ID`),
    INDEX `FK_bestelling_product_PRODUCT_ID`(`PRODUCT_ID`),
    UNIQUE INDEX `bestelling_product_BESTELLING_ID_PRODUCT_ID_key`(`BESTELLING_ID`, `PRODUCT_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `klant` (
    `ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `leverancier` (
    `ID` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `leverancier_klant` (
    `Leverancier_ID` INTEGER NOT NULL,
    `klanten_ID` INTEGER NOT NULL,

    INDEX `FK_leverancier_klant_klanten_ID`(`klanten_ID`),
    PRIMARY KEY (`Leverancier_ID`, `klanten_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `product` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `EENHEIDSPRIJS` DOUBLE NOT NULL,
    `FOTOURL` VARCHAR(255) NOT NULL,
    `INSTOCK` INTEGER NOT NULL,
    `NAAM` VARCHAR(255) NOT NULL,
    `LEVERANCIER_ID` INTEGER NOT NULL,

    INDEX `FK_product_LEVERANCIER_ID`(`LEVERANCIER_ID`),
    UNIQUE INDEX `product_LEVERANCIER_ID_NAAM_key`(`LEVERANCIER_ID`, `NAAM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DTYPE` VARCHAR(31) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `USERNAME` VARCHAR(255) NOT NULL,
    `BEDRIJF_ID` INTEGER NULL,

    UNIQUE INDEX `user_USERNAME_key`(`USERNAME`),
    INDEX `FK_user_BEDRIJF_ID`(`BEDRIJF_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `admin` ADD CONSTRAINT `FK_ADMIN_ID` FOREIGN KEY (`ID`) REFERENCES `user`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `bedrijf` ADD CONSTRAINT `FK_BEDRIJF_ADMIN_ID` FOREIGN KEY (`ADMIN_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `bedrijfverandering` ADD CONSTRAINT `FK_bedrijfverandering_AANGEVRAAGDDOOR_ID` FOREIGN KEY (`AANGEVRAAGDDOOR_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `bedrijfverandering` ADD CONSTRAINT `FK_BEDRIJFVERANDERING_BEDRIJF_ID` FOREIGN KEY (`BEDRIJF_ID`) REFERENCES `bedrijf`(`ID`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `bestelling` ADD CONSTRAINT `FK_BESTELLING_KLANT_ID` FOREIGN KEY (`KLANT_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `bestelling` ADD CONSTRAINT `FK_BESTELLING_LEVERANCIER_ID` FOREIGN KEY (`LEVERANCIER_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `bestelling` ADD CONSTRAINT `FK_BESTELLING_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `bestelling_product` ADD CONSTRAINT `FK_bestelling_product_BESTELLING_ID` FOREIGN KEY (`BESTELLING_ID`) REFERENCES `bestelling`(`ID`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `bestelling_product` ADD CONSTRAINT `FK_bestelling_product_PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `product`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `klant` ADD CONSTRAINT `FK_KLANT_ID` FOREIGN KEY (`ID`) REFERENCES `user`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `leverancier` ADD CONSTRAINT `FK_LEVERANCIER_ID` FOREIGN KEY (`ID`) REFERENCES `user`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `leverancier_klant` ADD CONSTRAINT `FK_LEVERANCIER_KLANT_Leverancier_ID` FOREIGN KEY (`Leverancier_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `leverancier_klant` ADD CONSTRAINT `FK_LEVERANCIER_KLANT_klanten_ID` FOREIGN KEY (`klanten_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `product` ADD CONSTRAINT `FK_PRODUCT_LEVERANCIER_ID` FOREIGN KEY (`LEVERANCIER_ID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `user` ADD CONSTRAINT `FK_USER_BEDRIJF_ID` FOREIGN KEY (`BEDRIJF_ID`) REFERENCES `bedrijf`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
